### ISSUE TITLE
Markdown not interpreted after installing

### ISSUE THREAD

**Issue by raphaelyancey** [daveis/manifesto-anchor-theme#5]
Articles are not parsed after installing the theme. It displays the raw markdown. Lacking an install note, I just renamed the original default theme to `default_` and named Manifesto theme to `default`. Everything works but that.

**Comment by PaulKish** [comment]
@raphaelyancey Noted the same, however looking through `article.php` line 58, I replaced `<?php echo article_html(); ?>` with `<?php echo article_markdown(); ?>` and now markdown is being interpreted

**Comment by raphaelyancey** [comment]
@PaulKish Works great, thank you. Maybe you want to send @daveis a pull request then?

**Comment by PaulKish** [comment]
@raphaelyancey I see an already pending pull request, hopefully @daveis will have some time to check it up

**Comment by daveis** [comment]
@raphaelyancey @PaulKish - my readme file notes that I am returning the html function for posts, as that is my preferred writing style. However it seems this is throwing a lot of people off so I will merge the pull request and make markdown the default once I'm back at a computer and not using my phone.

**Comment by daveis** [comment]
Merged pull request #4 from @morph027 . Closing this issue
